version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cointrace-db
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: cointrace
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
